<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-IKS9SD1L" failures="2" tests="11" name="TestNGPrograms.RetryTest" time="0.069" errors="0" timestamp="2023-01-02T07:41:47 IST" skipped="8">
  <testcase classname="TestNGPrograms.RetryTest" name="Second" time="0.006">
    <skipped/>
  </testcase> <!-- Second -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="First" time="0.002">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at TestNGPrograms.RetryTest.First(RetryTest.java:9)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- First -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="Second" time="0.003">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at TestNGPrograms.RetryTest.Second(RetryTest.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- Second -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="Second" time="0.012">
    <skipped/>
  </testcase> <!-- Second -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="First" time="0.002">
    <skipped/>
  </testcase> <!-- First -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="First" time="0.004">
    <skipped/>
  </testcase> <!-- First -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="Third" time="0.011"/>
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="First" time="0.006">
    <skipped/>
  </testcase> <!-- First -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="First" time="0.012">
    <skipped/>
  </testcase> <!-- First -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="Second" time="0.008">
    <skipped/>
  </testcase> <!-- Second -->
  <system-out/>
  <testcase classname="TestNGPrograms.RetryTest" name="Second" time="0.003">
    <skipped/>
  </testcase> <!-- Second -->
  <system-out/>
</testsuite> <!-- TestNGPrograms.RetryTest -->
